language: php
php:
  - '7.4'
  - '8.0'

before_install:
  - composer install
script: vendor/phpunit/phpunit/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
